CC/Models/BusinessLogic/Home/Filter.cs
using CC.Models.Classes;
using CC.Models.Classes.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CC.Models.BusinessLogic.Home
{
    public class Filter
    {
        public static FilterModel GetFilterModel()
        {
            var filterModel = new FilterModel();

            filterModel.TableList = new List<TableName>();
            filterModel.TableList.Add(new TableName { Id = 1, Name = "Lucrari efectuate" });
            filterModel.TableList.Add(new TableName { Id = 2, Name = "Materiale utilizate" });
            filterModel.TableList.Add(new TableName { Id = 3, Name = "Instrumente utilizate" });
            filterModel.TableList.Add(new TableName { Id = 4, Name = "Alte cheltuieli" });

            filterModel.OperationList = new Database.OperationEntities().Operations.ToList();

            filterModel.FilterList = new Database.FiltersEntities().Filters.AsQueryable()
                .Where(x => x.user_id == MySession.Current.UserGuid).ToList();

            filterModel.UserPermission = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Filters);
            
            return filterModel;
        }
    }
}

CC/Models/BusinessLogic/Home/Index.cs
using CC.Models.Classes.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CC.Models.BusinessLogic.Home
{
    public class Index
    {
        public static IndexModel GetIndexModel()
        {
            var model = new IndexModel
            {
                FiltersCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Filters).can_view ?? false,
                LoanMoneyCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.LoanMoney).can_view ?? false,
                SettingsCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Settings).can_view ?? false,
                SpecialitiesCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Speciality).can_view ?? false,
                UnitiesCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Units).can_view ?? false,
                UsersCanView = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Users).can_view ?? false
            };

            return model;
        }
    }
}

CC/Models/BusinessLogic/Home/LoanMoney.cs
using CC.Models.Classes;
using CC.Models.Classes.Home;
using CC.Models.Database;
using System.Linq;

namespace CC.Models.BusinessLogic.Home
{
    public class LoanMoney
    {
        public static LoanMoneyModel GetLoanMoneyModel()
        {
            var loanMoneyList = new LoanMoneyModel
            {
                LoanMoneyList = new LoanMoneyEntities().LoanMoney.ToList().Where(x => x.user_id == MySession.Current.UserGuid).ToList(),
                UserPermission = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.LoanMoney),
                CurrencyList = new CurrencyEntities().Currencies.ToList()
            };
            return loanMoneyList;
        }

        public static Database.LoanMoney GetLoanMoneyById(int loanMoneyId)
        {
            LoanMoneyEntities dbLoanMoney = new LoanMoneyEntities();
            return dbLoanMoney.LoanMoney.FirstOrDefault(x => x.id == loanMoneyId);
        }
    }
}

CC/Models/BusinessLogic/Home/LoanMoneyDetail.cs
using CC.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CC.Models.BusinessLogic.Home
{
    public class LoanMoneyDetail
    {

        public static List<Database.LoanMoneyDetail> GetLoanMoneyDetails()
        {
            Database.LoanMoneyDetailsEntities dbLoanMoneyDetails = new Database.LoanMoneyDetailsEntities();

            var model = dbLoanMoneyDetails.LoanMoneyDetails.AsQueryable()
                .Where(x => x.LoanMoneyId == MySession.Current.LoanMoneyId).ToList();

            return model;
        }

    }
}

CC/Models/BusinessLogic/Home/TranslateWord.cs
using System.Linq;
using CC.Models.Classes;
using CC.Models.Enums;

namespace CC.Models.BusinessLogic.Home
{
    public class TranslateWord
    {
        public static string GetWord(string word)
        {
            
            var translateWordRow = new Database.TranslateWordEntities().TranslateWords.AsQueryable()
                .FirstOrDefault(x => x.word == word);

            if (translateWordRow == null) return word;

            switch (MySession.Current.Language)
            {
                case LanguageTypes.Romanian:
                    word = translateWordRow.ro;
                    break;
                case LanguageTypes.Russian:
                    word = translateWordRow.ru;
                    break;
                case LanguageTypes.English:
                    word = translateWordRow.en;
                    break;
            }

            return word;
        }
    }
}

CC/Models/BusinessLogic/Home/Unit.cs
using CC.Models.Classes.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CC.Models.BusinessLogic.Home
{
    public class Unit
    {
        public static UnitModel GetUnitModel()
        {
            var unitModel = new UnitModel();

            unitModel.UnitList = new Database.ExcelentConstructUnit().Units.ToList();
            unitModel.UserPermission = User.UserPermissions.GetUserPermissionByModuleType(Enums.ModuleTypes.Units);

            return unitModel;
        }
    }
}

CC/Models/BusinessLogic/User/AspNetUser.cs
using CC.Models.Classes;
using CC.Models.Classes.Users;
using CC.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CC.Models.BusinessLogic.User
{
    public class AspNetUser
    {
        public static AspNetUserModel GetUserModel()
        {
            AspNetUserModel aspNetUserModel = new AspNetUserModel();

            switch (MySession.Current.IsUserAdmin)
            {
                case true:
                    aspNetUserModel.AspNetUserList = new Database.AspNetUsersEntities().AspNetUsers.ToList();                                                        
                    break;
                case false:
                    aspNetUserModel.AspNetUserList = new Database.AspNetUsersEntities().AspNetUsers
                                                        .ToList()
                                                        .Where(x => x.UserParentId == new Guid(MySession.Current.UserGuid))
                                                        .ToList();
                    break;
            }

            var result = new Database.AspNetUsersEntities().AspNetUsers.ToList();

            //result.First().AspNetRoles.First().Name;

            //aspNetUserModel.UserRoleList = GetUserRoleList();
                        
            return aspNetUserModel;
        }

        public static string GetUserRoleName(string userId)
        {
            var users = new Database.AspNetUsersEntities().AspNetUsers.ToList();

            return users.FirstOrDefault(x => x.Id == userId)?.AspNetRoles.FirstOrDefault()?.Name;
        }

        public static Database.AspNetUser GetUserById(string userId)
        {
            return new Database.AspNetUsersEntities().AspNetUsers.ToList().FirstOrDefault(x=>x.Id.Equals(userId));
        }
        
        //private static List<LocalUserRoles> GetUserRoleList()
        //{
        //    var dbRoles = new Database.AspNetUserRoleEntities().AspNetRoles.ToList();
        //    var dbUserRoles = new Database.AspNetUserRoleEntities().AspNetUserRoles.ToList();

        //    var userRoleList = new List<LocalUserRoles>();
        //    LocalUserRoles lur;
        //    foreach (var item in dbUserRoles)
        //    {
        //        lur = new LocalUserRoles();

        //        if (MySession.Current.UserRole == UserRoleType.Admin
        //            || item.AspNetRole.Name == UserRoleType.Manager.ToString()
        //            || item.AspNetRole.Name == UserRoleType.User.ToString())
        //        {
        //            lur.UserRoleID = item.RoleId;
        //            lur.UserID = item.UserId;
        //            lur.RoleName = item.AspNetRole.Name;

        //            if (lur.UserID != null)
        //                userRoleList.Add(lur);
        //        }
        //    }

        //    return userRoleList;
        //}
        
    }
}

CC/Models/BusinessLogic/User/UserPermissions.cs
using CC.Models.Classes;
using CC.Models.Classes.Users;
using CC.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using CC.Models.Database;
using DevExpress.Office.Utils;

namespace CC.Models.BusinessLogic.User
{
    public class UserPermissions
    {
        public static UserPermissionsModel GetUserPermissionModel(Guid guid, int moduleId)
        {
            var userPermissionList = new UserPermissionsEntities().UserPermissions.
                                                        AsQueryable().Where(x => x.user_id == guid).ToList();

            if (moduleId == 0)
                userPermissionList = userPermissionList.Where(x => x.item_id == 0).ToList();
            else userPermissionList = userPermissionList.Where(x => x.module_id == moduleId && x.item_id != 0).ToList();
            //
            Dictionary<int, string> dict = new Dictionary<int, string>();
            foreach (ModuleTypes item in Enum.GetValues(typeof(ModuleTypes)))
            {
                var text = string.Format("{0}", Home.TranslateWord.GetWord(item.ToString()));
                dict.Add((int)item, text);
            }

            var userPermissionModel = new UserPermissionsModel
            {
                ModuleList = dict,
                UserPermissionList = userPermissionList,
                ItemList = GetItemList(moduleId)
            };

            return userPermissionModel;
        }

        public static void SetUserPermissions()
        {
            switch (MySession.Current.UserRole)
            {
                case UserRoleType.Admin:
                    MySession.Current.UserPermisionList = SetDefaultUserPermission(true);
                    break;
                case UserRoleType.Manager:
                    MySession.Current.UserPermisionList = SetDefaultUserPermission(true);
                    SetDatabasePermissions();
                    break;
                case UserRoleType.User:
                    MySession.Current.UserPermisionList = SetDefaultUserPermission(false);
                    SetDatabasePermissions();
                    break;
                default:
                    MySession.Current.UserPermisionList = SetDefaultUserPermission(false);
                    SetDatabasePermissions();
                    break;
            }
        }

        private static List<UserPermission> SetDefaultUserPermission(bool up)
        {
            var userPermission = new List<UserPermission>();

            foreach (var item in Enum.GetValues(typeof(ModuleTypes)))
            {
                userPermission.Add(new UserPermission
                {
                    module_id = (int)item,
                    can_view = up,
                    can_add = up,
                    can_delete = up,
                    can_edit = up
                });
            }
            
            return userPermission;
        }
        
        private static void SetDatabasePermissions()
        {
            var userPermissionList = new UserPermissionsEntities().UserPermissions.
                AsQueryable().Where(x => x.user_id == new Guid(MySession.Current.UserGuid)).ToList();

            foreach (var item in userPermissionList)
            {
                var userPermission = MySession.Current.UserPermisionList
                    .FirstOrDefault(x => x.module_id == item.module_id);

                if (userPermission != null)
                {
                    userPermission.can_view = item.can_view;
                    userPermission.can_edit = item.can_edit;
                    userPermission.can_delete = item.can_delete;
                    userPermission.can_add = item.can_add;
                }
            }
        }

        public static UserPermission GetUserPermissionByModuleType(ModuleTypes moduleName)
        {
            if (MySession.Current.UserPermisionList == null) return new UserPermission();

            var up = MySession.Current.UserPermisionList.FirstOrDefault(x => x.module_id == (int)moduleName);
        
            if(up == null)
                up = new UserPermission();

            return up;
        }

        public static Dictionary<int, string> GetItemList(int moduleId)
        {
            var itemList = new Dictionary<int, string>();
            
            switch (moduleId)
            {
                case (int)ModuleTypes.Objects:
                    itemList = Object.Object.GetObjectModel().ObjectList.ToList()
                        .Where(x => x.UserId == MySession.Current.UserGuid)
                        .Select(x => new {id = x.ID, name = x.Address})
                        .AsEnumerable()
                        .ToDictionary(dic => dic.id, dic => dic.name);
                    break;
            }

            return itemList;
        }

        public static List<int> GetModuleItemIds(ModuleTypes moduleType)
        {
            var result = new UserPermissionsEntities().UserPermissions.AsQueryable()
                .Where(x => x.user_id == new Guid(MySession.Current.UserGuid)
                            && x.module_id == (int)moduleType
                            && x.item_id != 0).AsEnumerable()
                .Select(x => x.item_id).ToList();

            return result;
        }
    }

}

CC/Controllers/SettingController.cs
using CC.Models.Classes;
using DevExpress.Web.Mvc;
using System;
using System.Linq;
using System.Web.Mvc;
using Database = CC.Models.Database;
using BLSetting = CC.Models.BusinessLogic.Setting;

namespace CC.Controllers
{
    public class SettingController : Controller
    {
        // GET: Settings
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Setting()
        {
            return View();
        }

        Database.ExcelentConstructSetting dbSetting = new Database.ExcelentConstructSetting();
        Database.AspNetUsersEntities aspNetUsersEntities = new Database.AspNetUsersEntities();
        Database.SettingStatusEntities settingStatusEntities = new Database.SettingStatusEntities();

        [ValidateInput(false)]
        public ActionResult GridViewSettingPartial()
        {
            var settingModel = BLSetting.Setting.GetSettingModel(aspNetUsersEntities, dbSetting);
            return PartialView("_GridViewSettingPartial", settingModel);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewSettingPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Database.Setting item)
        {
            var model = dbSetting.Settings;
            if (ModelState.IsValid)
            {
                try
                {
                    item.UserId = MySession.Current.UserGuid;
                    //item.Name = 
                    model.Add(item);
                    dbSetting.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else ViewData["EditError"] = "Please, correct all errors.";
            BLSetting.Setting.SetSetting(BLSetting.Setting.GetSettingForCurrentUserList(dbSetting));
            //
            var settingModel = BLSetting.Setting.GetSettingModel(aspNetUsersEntities, dbSetting);
            return PartialView("_GridViewSettingPartial", settingModel);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewSettingPartialUpdate(Database.Setting item)
        {
            var model = dbSetting.Settings;
            if (ModelState.IsValid)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.ID == item.ID);
                    if (modelItem != null)
                    {
                        this.UpdateModel(modelItem);
                        dbSetting.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            BLSetting.Setting.SetSetting(BLSetting.Setting.GetSettingForCurrentUserList(dbSetting));
            //
            var settingModel = BLSetting.Setting.GetSettingModel(aspNetUsersEntities, dbSetting);
            return PartialView("_GridViewSettingPartial", settingModel);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewSettingPartialDelete(System.Int32 ID)
        {
            var model = dbSetting.Settings;
            if (ID >= 0)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.ID == ID);
                    if (item != null)
                        model.Remove(item);
                    dbSetting.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            BLSetting.Setting.SetSetting(BLSetting.Setting.GetSettingForCurrentUserList(dbSetting));
            //
            var settingModel = BLSetting.Setting.GetSettingModel(aspNetUsersEntities, dbSetting);
            return PartialView("_GridViewSettingPartial", settingModel);
        }
    }
}

CC/Views/Home/Customer.cshtml
@Html.DevExpress().GetStyleSheets(
new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
)
@Html.DevExpress().GetScripts(
new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new Script { ExtensionSuite = ExtensionSuite.Editors }
)

@{
    ViewBag.Title = "Customer";
}

<h2>Clienți</h2>


@Html.Action("CustomerPartial")

CC/Views/Home/Customers.cshtml
@Html.DevExpress().GetStyleSheets(
new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
)
@Html.DevExpress().GetScripts(
new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new Script { ExtensionSuite = ExtensionSuite.Editors }
)

@{
    ViewBag.Title = "Customer";
}

<h2>Clienți</h2>


@Html.Action("CustomerPartial")

CC/Views/Home/Index.cshtml
@model CC.Models.Classes.Home.IndexModel

<br><br>
<div class="index-icon-row">
    <div>
        @if (Model.SettingsCanView)
        {
            <span><b>Setări</b></span>
            @Html.ActionLink("Report", "Setting", new { controller = "Setting" }, new { @class = "settingIcon" })
        }
    </div>
    <div>
        @if (Model.UnitiesCanView)
        {
            <span><b>Unități măsură</b></span>
            @Html.ActionLink("Report", "Unit", new { controller = "Home" }, new { @class = "unitsIcon", Model.UnitiesCanView })
        }
    </div>
    <div>
        @if (Model.SpecialitiesCanView)
        {
            <span><b>Specialități</b></span>
            @Html.ActionLink("Report", "Speciality", new { controller = "Home" }, new { @class = "specialityIcon" })
        }
    </div>
</div>
<div class="index-icon-row">
    <div>
        @if (Model.LoanMoneyCanView)
        {
            <span><b>Împrumuturi</b></span>
            @Html.ActionLink("Report", "LoanMoney", new { controller = "Home" }, new { @class = "loanMoneyIcon" })
        }
    </div>
    <div>
        @if (Model.FiltersCanView)
        {
            <span><b>Filtre</b></span>
            @Html.ActionLink("Report", "Filter", new { controller = "Home" }, new { @class = "filtersIcon" })
        }
    </div>

    <div>
        @if (Model.UsersCanView)
        {
            <span><b>Utilizatori</b></span>
            @Html.ActionLink("Utilizatori", "Users", new { controller = "Users" }, new { @class = "usersIcon" })
        }
    </div>
</div>

CC/Views/Home/Overview.cshtml
@Html.DevExpress().GetStyleSheets(
new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }
)
@Html.DevExpress().GetScripts(
new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new Script { ExtensionSuite = ExtensionSuite.Editors },
new Script { ExtensionSuite = ExtensionSuite.GridView }
)


@{
    ViewBag.Title = "Overview";
}

<h2>Overview</h2>

@model DevExpress.XtraReports.UI.XtraReport
@Html.DevExpress().WebDocumentViewer(settings =>
{
    settings.Name = "documentViewer";
}).Bind(Model).GetHtml()

CC/Views/Home/Specialities.cshtml
@Html.DevExpress().GetStyleSheets(
new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
)
@Html.DevExpress().GetScripts(
new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
new Script { ExtensionSuite = ExtensionSuite.Editors }
)

@{
    ViewBag.Title = "Specialities";
}

<h2>Specialities</h2>

@Html.Action("GridViewSpeciality")

CC/Views/Home/TranslateWords.cshtml
@Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
    )
@Html.DevExpress().GetScripts(
    new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new Script { ExtensionSuite = ExtensionSuite.Editors }
    )

@{
    ViewBag.Title = "TranslateWords";
}

<h2>TranslateWords</h2>


@Html.Action("GridViewTranslateWordsPartial")

CC/Views/Home/_GridViewFilterPartial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "GridViewFilter";
        settings.CallbackRouteValues = new { Controller = "Home", Action = "GridViewFilterPartial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Home", Action = "GridViewFilterPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Home", Action = "GridViewFilterPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Home", Action = "GridViewFilterPartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = Model.UserPermission.can_add ?? false;
        settings.CommandColumn.ShowDeleteButton = Model.UserPermission.can_delete ?? false;
        settings.CommandColumn.ShowEditButton = Model.UserPermission.can_edit ?? false;

        settings.KeyFieldName = "id";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;

        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.Off;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;

        //settings.Columns.Add("id");
        //settings.Columns.Add("controller_id");
        settings.Columns.Add(c =>
        {
            c.FieldName = "table_name_id";
            c.Caption = "Nume tabel";
            c.EditorProperties().ComboBox(p =>
            {
                p.TextField = "Name";
                p.ValueField = "Id";
                p.ValueType = typeof(int);
                p.DataSource = Model.TableList;
            });
        });
        settings.Columns.Add(c =>
        {
            c.FieldName = "column_name";
            c.Caption = "Coloana Filtrata";
        });

        settings.Columns.Add(c =>
        {
            c.FieldName = "operation_id";
            c.Caption = "Operatie";
            c.EditorProperties().ComboBox(p =>
            {
                p.TextField = "math_operation";
                p.ValueField = "Id";
                p.ValueType = typeof(int);
                p.DataSource = Model.OperationList;
            });
        });

        settings.Columns.Add(c =>
        {
            c.FieldName = "compare_value";
            c.Caption = "Valoarea";
        });
        
    });
    if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model.FilterList).GetHtml()

CC/Views/Home/_GridViewPartial.cshtml
@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "GridView";
        settings.CallbackRouteValues = new { Controller = "Home", Action = "GridViewPartial" };

		settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Home", Action = "GridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Home", Action = "GridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Home", Action = "GridViewPartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

		settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = true;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;

		settings.KeyFieldName = "ID";

		settings.SettingsPager.Visible = true;
		settings.Settings.ShowGroupPanel = true;
		settings.Settings.ShowFilterRow = true;
		settings.SettingsBehavior.AllowSelectByRowClick = true;

		settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.Off;
		settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
		settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
		settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
		settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;

				settings.Columns.Add("username");
				settings.Columns.Add("password");
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()

CC/Views/Home/_GridViewSpeciality.cshtml
@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "GridView";
        settings.CallbackRouteValues = new { Controller = "Home", Action = "GridViewSpeciality" };

				settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Home", Action = "GridViewSpecialityAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Home", Action = "GridViewSpecialityUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Home", Action = "GridViewSpecialityDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

		settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = true;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;

		settings.KeyFieldName = "id";

		settings.SettingsPager.Visible = true;
		settings.Settings.ShowGroupPanel = true;
		settings.Settings.ShowFilterRow = true;
		settings.SettingsBehavior.AllowSelectByRowClick = true;

		settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.Off;
		settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
		settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
		settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
		settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;

				settings.Columns.Add("name");
				settings.Columns.Add("UserId");
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()